#!/bin/sh

set -e

if ! psql -U postgres -d lurch --quiet -c '' 2>/dev/null; then
  echo Initializing the database.
  /usr/bin/pg_ctlcluster 13 main start
  psql -U postgres -f /dev/stdin --quiet < /lurch/schema.sql
  cd /lurch && /lurch/populate
fi

/usr/sbin/lighttpd -f /lurch/lighttpd.conf

# FIXME: https://github.com/rixed/lurch/issues/60
#exec /lurch/www/lurch step --loop
while sleep 1; do
  /lurch/www/lurch step
done
