#!/bin/sh

set -e

# This can be configured, and match what's in db/backup:

instance_name=lurchdb
db_port=5433
db_pwd=secret
db_docker_image=postgres

# Create a docker instance of postgres:

db_container=$(docker run --name $instance_name -p $db_port:5432 -e POSTGRES_PASSWORD=$db_pwd --detach $db_docker_image -c work_mem=1GB)

echo "DB running in docker container $db_container"

echo "Waiting for postgres service..."
while ! docker exec $instance_name psql --quiet -U postgres -c 'SELECT 1;' > /dev/null 2>&1 ; do
  echo 'Waiting some more...'
  sleep 1
done

echo 'Creating database (message about DB not existing is OK)...'
docker exec -i $instance_name psql --quiet -U postgres -f /dev/stdin --quiet < db/schema.sql

# Also:
echo 'Creating cgroup'
sudo cgcreate -a "$USER" -t "$USER" -g cpuacct,memory:lurch

echo 'Done.'
