#!/bin/sh

set -e

www/lurch import -o 'test container' << EOF
(isolate
  (docker "rixed/lurch-docker-in-docker")
  (exec "" "/usr/bin/docker"
    ("ps")
    () null))
EOF

www/lurch import -o 'test chroot' << EOF
(isolate
  (chroot "busybox")
  (exec "" "/bin/ls"
    ("/bin")
    () null))
EOF

www/lurch import -o 'test build' << EOF
(isolate
  (docker "debian:stable-slim")
  (sequence
    (exec "" "/usr/bin/apt-get"
      ("update")
      () null)
    (exec "" "/usr/bin/apt-get"
      ("install" "--no-install-recommends" "--quiet" "--yes"
       "git" "gcc" "make" "ocaml-nox" "opam" "libpq-dev" "imagemagick")
      () null)
    (exec "" "/usr/bin/opam"
      ("init" "--no-setup" "--disable-sandboxing")
      () null)
    (exec "" "/usr/bin/opam"
      ("update" "--yes")
      () null)
    (exec "" "/usr/bin/opam"
      ("repo" "add" "--set-default" "ocalme"
       "git://github.com/rixed/ocalme-opam-repository.git")
      () null)
    (exec "" "/usr/bin/opam"
      ("repo" "priority" "ocalme" "1")
      () null)
    (exec "" "/usr/bin/opam"
      ("update" "--yes")
      () null)
    (exec "" "/usr/bin/opam"
      ("install" "--yes" "batteries" "cgi" "cmdliner" "js_of_ocaml"
       "js_of_ocaml-ppx" "js_of_ocaml-ppx_deriving_json" "ppx_deriving"
       "ocamlfind" "postgresql" "qtest" "syslog" "ocaml-vdom")
      () null)
    (exec "" "/usr/bin/git"
      ("clone" "https://github.com/rixed/lurch.git")
      () null)
    (exec "/lurch" "/bin/sh"
      ("-c" "./configure && make && make check")
      ("OPAM_SWITCH_PREFIX=/root/.opam/default"
       "CAML_LD_LIBRARY_PATH=/root/.opam/default/lib/stublibs:/usr/local/lib/ocaml/4.11.1/stublibs:/usr/lib/ocaml/stublibs"
       "OCAML_TOPLEVEL_PATH=/root/.opam/default/lib/toplevel"
       "MANPATH=:/root/.opam/default/man"
       "PATH=/root/.opam/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin") null)))
EOF
